### ISSUE TITLE
Way to set backend images repo url

### ISSUE THREAD

**Issue by javond-cap** [DataDog/KubeHound#316]
## Problem :

I work with an environment without internet access,
I need to get images from a relay image repository,
Is there a way to configure kubehound to set backends images url ?

## Solution :

A way to set each service image url in config file

**Comment by Zenithar** [comment]
Hello, thank you for your contribution.

To confirm: you are looking for a way to override docker images pulled during the `kh backend` command so that you could pull them from a different registry?

**Comment by javond-cap** [comment]
Hello, you're welcome 😸 

That's exactly what I want to do.

**Comment by Zenithar** [comment]
You should be able to reuse the docker compose file - https://github.com/DataDog/KubeHound/blob/main/deployments/kubehound/docker-compose.yaml - and add an override to this file.

Create a `docker-compose.overrides.yaml` file, which such content:

```yaml
name: kubehound-release
services:
  mongodb:
    image: your.registry.tld/mongo/mongo:6.0.6
    ports:
      - "127.0.0.1:27017:27017"

  kubegraph:
    image: your.registry.tld/datadog/kubehound-graph:latest
    ports:
      - "127.0.0.1:8182:8182"
      - "127.0.0.1:8099:8099"
  
  ui-jupyter:
    image: your.registry.tld/datadog/kubehound-ui:latest

  ui-invana-engine:
    image: your.registry.tld/invanalabs/invana-engine:latest

  ui-invana-studio:
    image: your.registry.tld/invanalabs/invana-studio:latest
```

Then invoke the `kh backend` command this way:

```bash
$ kh backend -f docker-compose.yaml docker-compose.overrides.yaml
```
